disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - file_name_no_space
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - legacy_nsgeometry_functions
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_file_private
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher

excluded:
  - Carthage
  - Pods
  - .build
  - Package.swift

line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 10

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

identifier_name:
  min_length: 3
  max_length: 40
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k

reporter: "xcode"
